version: '3.3'
services:
    sharelatex:
      restart: unless-stopped
      image: sharelatex/sharelatex:4.2.3
      container_name: sharelatex
      env_file:
        - ./.env
      volumes:
        - /srv/overleaf/data:/var/lib/sharelatex
      environment:        
        OVERLEAF_SITE_URL: "https://${OVERLEAF_DOMAIN}"
        OVERLEAF_SECURE_COOKIE: "true"
        OVERLEAF_BEHIND_PROXY: "true"
        # Email settings
        OVERLEAF_EMAIL_SMTP_HOST: "protonmail-bridge"
        OVERLEAF_EMAIL_SMTP_PORT: 25
        # https://nodemailer.com/smtp/#tls-options
        # causes to use STARTTLS if available
        OVERLEAF_EMAIL_SMTP_SECURE: "false"
        # allows self-signed certificates
        OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: "false"
        # allows using STARTTLS if available
        OVERLEAF_EMAIL_SMTP_IGNORE_TLS: "false"
        # logs to /var/log/sharelatex/web.log
        OVERLEAF_EMAIL_SMTP_LOGGER: "true"
        # service "mongo" is the MongoDB host
        OVERLEAF_MONGO_URL: "mongodb://mongo/sharelatex"
        # service "redis" is the Redics Cache host
        REDIS_HOST: "redis"
        REDIS_PORT: 6379
        OVERLEAF_REDIS_HOST: "redis"
        OVERLEAF_REDIS_PORT: 6379
        V1_HISTORY_URL: "http://sharelatex:3100/api"
        # server pro settings
        GIT_BRIDGE_ENABLED: "false"

      labels:
        # activate traefik
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.sharelatex-https-redirect.redirectscheme.scheme=https
        # do we need to activate this middleware?
        - traefik.http.middlewares.sharelatex-header.headers.referrerPolicy=no-referrer
        - traefik.http.middlewares.sharelatex-header.headers.stsSeconds=15552000
        - traefik.http.middlewares.sharelatex-header.headers.forceSTSHeader=true
        - traefik.http.middlewares.sharelatex-header.headers.stsPreload=true
        - traefik.http.middlewares.sharelatex-header.headers.stsIncludeSubdomains=true
        - traefik.http.middlewares.sharelatex-header.headers.browserXssFilter=true
        - traefik.http.middlewares.sharelatex-header.headers.customRequestHeaders.X-Forwarded-Proto=https

        - traefik.http.routers.sharelatex.entrypoints=http
        - traefik.http.routers.sharelatex.rule=Host(`${OVERLEAF_DOMAIN}`)
        - traefik.http.routers.sharelatex.middlewares=sharelatex-https-redirect
        
        - traefik.http.routers.sharelatex-https.rule=Host(`${OVERLEAF_DOMAIN}`)
        - traefik.http.routers.sharelatex-https.entrypoints=https
        - traefik.http.routers.sharelatex-https.tls=true
        - traefik.http.routers.sharelatex-https.tls.certresolver=le
        - traefik.http.routers.sharelatex-https.service=sharelatex
        - traefik.http.services.sharelatex.loadbalancer.server.port=80
      depends_on:
        - mongo
        - redis
      networks:
        - overleaf
        - traefik-public
        - protonmail-network

    mongo:
      image: mongo:5.0
      container_name: sharelatex-mongo
      restart: unless-stopped
      command: --replSet overleaf
      env_file:
        - .env
      volumes:
        - mongo:/data/db
      expose:
        - 27017
      healthcheck:
        test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
        interval: 10s
        timeout: 10s
        retries: 5
      networks:
        - overleaf

    redis:
      image: redis:6.2
      container_name: sharelatex-redis
      restart: unless-stopped
      env_file:
        - ./.env
      volumes:
        - redis:/data
      networks:
        - overleaf

volumes:
  mongo:
  redis:

networks:
  overleaf:
    driver: bridge
  traefik-public:
    external: true
  protonmail-network:
    external: true
